### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by AhmadSaeed68** [Priyanshu-hawk/ChatGPT-unofficial-api-selenium#1]
Traceback (most recent call last):
  File "C:\Users\BOB\PycharmProjects\ChatGPT-unofficial-api-selenium\chrome_handler.py", line 13, in <module>
    start_chrome()
  File "C:\Users\BOB\PycharmProjects\ChatGPT-unofficial-api-selenium\chrome_handler.py", line 7, in start_chrome
    subprocess.Popen(['google-chrome','--remote-debugging-port=9222','--user-data-dir=chromedata'],stdout = subprocess.PIPE, stderr = subprocess.PIPE)
  File "C:\Users\BOB\anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\BOB\anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Priyanshu-hawk** [comment]
Have you created debugging browser? and login to chatGPT with it?

Follow This step if not - https://github.com/Priyanshu-hawk/ChatGPT-unofficial-api-selenium#1-start-the-remote-chrome-browser
