### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'click'

### ISSUE THREAD

**Issue by dankarthik25** [Priyanshu-hawk/ChatGPT-unofficial-api-selenium#10]
I am using LinuxMint  
I had to reinstall my chrome because selenium session is not supported after when i run  `python api_backend.py` <br>
It is showing me error 
```
06/14/2024 05:51:28 PM - ERROR: # Element '//*[contains(text(), 'Log in with your OpenAI account to continue')]' is not present.<br>
Already logged in<br>
06/14/2024 05:51:50 PM - ERROR: # Element '//*[contains(text(), 'Tips for getting started')]' is not present.<br>
06/14/2024 05:51:50 PM - ERROR: # Element '//*[contains(text(), 'Tips for getting started')]' is not present.<br>
No guidlines found<br>
Enter text: hi how are you doing<br>
06/14/2024 05:52:27 PM - ERROR: # Element '//*[@data-testid='send-button']' is not present.<br>
06/14/2024 05:52:27 PM - ERROR: # Element '//*[@data-testid='send-button']' is not found.<br>
Traceback (most recent call last):<br>
  File "/media/karthik/myVolume/Project_Python/ChatGPT-unofficial-api-selenium/api_backend.py", line 127, in <module><br>
    resp = make_gpt_request(req)<br>
           ^^^^^^^^^^^^^^^^^^^^^<br>
  File "/media/karthik/myVolume/Project_Python/ChatGPT-unofficial-api-selenium/api_backend.py", line 94, in make_gpt_request<br>
    send_btn.click()<br>
    ^^^^^^^^^^^^^^<br>
AttributeError: 'bool' object has no attribute 'click' <br>
```

**Comment by Priyanshu-hawk** [comment]
Hello @dankarthik25 , i will update the code soon. Since ChatGPT UI has been updated so elements are changed so the code is not able to locate correct button.

**Comment by Priyanshu-hawk** [comment]
Code has been updated!!, take a pull and retry!!
