### ISSUE TITLE
Support for headless browser

### ISSUE THREAD

**Issue by arnabkuw** [Priyanshu-hawk/ChatGPT-unofficial-api-selenium#14]
Hi Priyanshu,

Great work! However, I noticed that it doesn't support the headless browser operation. when I pass the following options:
```
    options.add_argument("--headless")  # Run browser in headless mode
    options.add_argument("--no-sandbox")  # Bypass OS security model
    options.add_argument("--disable-web-security")
```
in the load-chrome() function, I get the following error:

```
09/07/2024 03:56:43 PM - ERROR: # Element '//*[@id='prompt-textarea']' is not present.
09/07/2024 03:56:43 PM - ERROR: # Element '//*[@id='prompt-textarea']' is not present.
Traceback (most recent call last):
  File "d:\TrueMedia_Internship\wrapper_ui\ChatGPT-unofficial-api-selenium\api_backend.py", line 106, in <module>
    resp = make_gpt_request(req)
           ^^^^^^^^^^^^^^^^^^^^^
  File "d:\TrueMedia_Internship\wrapper_ui\ChatGPT-unofficial-api-selenium\api_backend.py", line 79, in make_gpt_request
    EC.presence_of_element_located((By.XPATH, send_btn_xpath))
                                              ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'send_btn_xpath' where it is not associated with a value
```

Let me know if there's any workaround for this

**Comment by Priyanshu-hawk** [comment]
Hello @arnabkuw , sorry for late reply. i tested with headless mode and it is failing at my end too. currently undetected_chromedriver is used maybe that is why chatgpt is blocking.

We can try vanilla chromedriver and and check with those parameters. Can you try it once!?

**Comment by Maxhem2** [comment]
Consider moving to SeleniumBase

**Comment by Priyanshu-hawk** [comment]
First of all, apologies @Maxhem2  for the delayed response, I've been quite busy lately. I checked out SeleniumBase, and it seems very promising. Could you create a separate branch for SB so we can test it before deploying it to the main branch?

Thank you for letting us know about SB! It makes headless browsing much easier.

**Comment by Maxhem2** [comment]
Unfortunately, my use case is quite different, and I won't be able to work on creating a separate branch for SB at this time. My current schedule is very tight, and I don't have the bandwidth to dedicate to this.

Best regards, Maxhem2

**Comment by Priyanshu-hawk** [comment]
I understand, @Maxhem2. I’ll try to get this implemented on the main branch. Thank you once again!

**Comment by plscarrymeeeeeeee** [comment]
i would love to see this project with SeleniumBase. any new updates?

**Comment by Priyanshu-hawk** [comment]
Apology @plscarrymeeeeeeee for the late response, been busy these days. I'd like to invite you to update/modify the code for seleniumbase compatibility. This would be great.
